version: "3.8"
services:
  mysql:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_root
      MYSQL_DATABASE: expressPrisma
      MYSQL_USER: express_prisma
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
