services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    volumes:
      - localstacks_vol:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  mysql:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_root
      MYSQL_DATABASE: expressPrisma
      MYSQL_USER: express_prisma
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  localstacks_vol:
